# Generated by Django 5.1.5 on 2025-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='property',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent_phone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='\\static\\website\\img\\logo.jpg', upload_to='property_images'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
