# Generated by Django 5.1.5 on 2025-02-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_booking_property_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
