# Generated by Django 5.1.5 on 2025-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_property_latitude_remove_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_for',
            field=models.CharField(default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='house', max_length=10),
        ),
    ]
