# Generated by Django 5.1.5 on 2025-02-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_property_for_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=122),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('office', 'Office')], default='villa', max_length=122),
        ),
    ]
