# Generated by Django 5.1.5 on 2025-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_property_property_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('unavailable', 'Unavailable'), ('sold', 'Sold')], default='available', max_length=122),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='static/website/img/logo.jpg', upload_to='property_images'),
        ),
    ]
